### PR TITLE
feat(performance tab): Add initial structure for performance tab

### PR DESCRIPTION
**Pull request by SomeKittens**
Add a perf item for inspected app, create a performance tab, add some basic stylings.
Calculate total time taken per-watcher.

We're finally adding performance back into the mix!  Styling is fairly utilitarian at this point.

### TODO:

- [x] Add graph from https://github.com/kentcdodds/ng-stats (thanks, @kentcdodds !)
- [x] Pull out watchers with a time of zero (irrelevant)
- [x] Stats on last N digest cycles
- [x] # of watchers in last digest cycle

### CODE REVIEW

**Comment by SomeKittens** [comment]
(I'll be rebasing all these commits down before PR is ready)

**Comment by SomeKittens** [comment]
Ready for review, will compress to a single commit when everyone's ok with the current state.

**Comment by kentcdodds** [comment]
Wow, I feel like you improved on my implementation big time. At least there's a lot less code! Good work :+1:

**Comment by btford** [comment]
:clap: bravo!

**Comment by erwinmombay** [comment]
:+1:

**Comment by btford** [comment]
LGTM

**Comment by erwinmombay** [comment]
landed via https://github.com/angular/batarang/commit/f8359a9f410a173397f461a6ffc14c4b52ad2990

**Pull request merged**
