### PR TITLE
Show brief information for each scope on 'Model' and 'Performance' tabs

### PR DESCRIPTION
**Pull request by AlexeyGrishin**
Hi,

I think it would be useful to see something more descriptive than 'Scope (<id>)' in the Models and Performance tabs. This change adds some brief information about scope - at least controller name, directive name, ng-include source and ng-repeat item description.

Also you may define scope attribute __name in your controller/directive and it will be shown instead of id.

Please refer to the screenshots:
### Before

batarang-todo-before
### After

batarang-todo-after
### Before

batarang-before
### After

batarang-after
### Known issues
- nothing specific is shown for ngView/ngSwitch
- directive name is shown only if 'replace' flag is not set to 'true'
- scope names are collected on each 'poll' event for Performance tab even nothing is changed. There shall be caching for it.

Looking for your feedback, thanks.

[Review on Reviewable](https://reviewable.io/reviews/angular/angularjs-batarang/99)

### CODE REVIEW

**Comment by SomeKittens** [comment]
We'd love to bring this into current master if you don't mind bringing it up to date.

**Comment by SomeKittens** [comment]
No response, closing.

**Comment by g-patel** [comment]
@johnschult how's ng-inspector been working out for you? I tried it, but it's not useful at all as it freezes my chrome tab all the time.

**Comment by g-patel** [comment]
Why was this PR not merged?

**Pull request closed without merging**
