### PR TITLE
Added a "pin" button on models view (scroll up/down models view with a large scope tree is really annoying)

### PR DESCRIPTION
**Pull request by darlanalves**
Using the Models tab with a lot of scopes is really annoying. To view some scopes, I needed to scroll down the tree on the left, and scroll up to view the model, then scroll down again, and so on... Also, I removed that weird grayed background on scope tree. With more than 3 or 4 scope levels, the links become unreadable.

[Review on Reviewable](https://reviewable.io/reviews/angular/angularjs-batarang/87)

### CODE REVIEW

**Comment by solarisy** [comment]
+1

**Comment by SomeKittens** [comment]
We can't merge a branch with conflicts.  +1's don't help that.  If you're interested in this coming into core, update the PR.

**Comment by darlanalves** [comment]
@SomeKittens this pull request was open almost two years ago, and at the time, there were no conflicts. I tried to ping some core members on twitter to review it, to no avail.

I used my own version for a while, but I don`t think it make sense anymore. The new version of batarang (v0.9.1) is working just fine, and I can`t even remember what was changed at the time. 

I think you can close the pull request. The files changed in the older version don`t exist anymore.

**Comment by DmitryEfimenko** [comment]
that's a shame

**Comment by SomeKittens** [comment]
@darlanalves Thanks for the enthusiasm, and sorry about the non-response.  I promise, we won't take two years in the future!

**Pull request closed without merging**
