### PR TITLE
Allow to inspect Angular2+ component inspection

### PR DESCRIPTION
**Pull request by yannickglt**
The goal of this feature is to provide a very simple way to inspect an Angular component instance. It should be as easy as inspecting an AngularJS scope with Batarang.
I think it will help users used to AngularJS and Batarang to start development and debug on Angular2+.

**Example of Angular2 debugging with Batarang**

Related to https://github.com/angular/batarang/issues/235

### CODE REVIEW

**Comment by yannickglt** [comment]
I signed it!

**Comment by yannickglt** [comment]
@gary-b @gkalpak Is there something I should change to get this PR merged, or maybe this is not a wanted feature?

**Comment by gkalpak** [comment]
Sorry for taking so long to respond, @yannickglt. We discussed it internally and we think it will be more confusing than helpful. Besides, there is already [Augury][1], which is excellent for exploring/debugging Angular applications.

It would be great if Batarang detected Angular apps and showed a message pointing the user to Augury for debugging Angular apps.

##
I am going to close this PR, since it is not a feature we want to include in Batarang, but you are more than welcome to open a new one for pointing to Augury :smiley:

[1]: https://augury.angular.io/

**Comment by yannickglt** [comment]
It's OK! Thanks for answering anyway.

Actually, I already made a similar pull request on [Augury](https://github.com/rangle/augury/pull/1202) but I guess the main contributors are as busy as you are because I could not get any reply for the moment.

I currently work with both Batarang and Augury and the main difference I can see is that Batarang is loaded in the elements panel, while Augury loads only when accessing its own panel. It means that I need to click on the Augury tab first, wait for the plugin to be loaded and then select a DOM element in the elements panel to be able to inspect my component. It's quite annoying and confusing 😕  and got me keep using Batarang and `$scope` for my Angular apps.

**Pull request closed without merging**
