### PR TITLE
fix(devTools) correct url to dev tools page

### PR DESCRIPTION
**Pull request by gary-b**
Dev tools displays a page not found error in the Batarang 0.8.4 release - fixing this.

### CODE REVIEW

**Comment by gary-b** [comment]
Looks like there is a second issue were the ElementPanel just displays an error. Added a fix for this - not great code though.

**Comment by gary-b** [comment]
Related to #242.

**Comment by allentong** [comment]
Will this get automatically get deployed to the Chrome Web Store?

**Comment by gary-b** [comment]
A new deployment can be made by the maintainers after the issues are fixed. I believe they are looking into it.

**Comment by allentong** [comment]
Thanks for the update

**Comment by erwinmombay** [comment]
Thanks, hopefully the build is green!

**Comment by erwinmombay** [comment]
@gary-b if its green, do you mind squashing this into one commit?

**Comment by gary-b** [comment]
Still failing unfortunately.

**Comment by erwinmombay** [comment]
@gary-b no problem, looking into this too. trying a full blown revert in case this isnt related to code.

**Comment by erwinmombay** [comment]
so this is also failing https://github.com/angular/batarang/pull/243 (which is a revert of the changes we pulled in today). was expecting this to pass

**Comment by gary-b** [comment]
I am not sure what is going on with the saucelabs tests. I tried doubling the karma config setting captureTimeout to 120000ms but it still failed. Trying with chrome 43 also failed. I've undone both those changes and squashed what I have down to a single commit. Might not get to look at it again tonight.

**Comment by btford** [comment]
The sauce labs tests are a separate issue. Let's worry about fixing Batarang and cutting another release, and then follow up to investigate sauce labs.

**Pull request closed without merging**
